env:
  global:
  # COVERITY_SCAN_TOKEN
  - secure: "WMYNPfcutYahs6gFjPKNxvS0lpL7JXpvzgaxlV58HMxQcgD/ccJX3J7rkYySNA6N2jTZn1Pzv5BLZqyEZi2iODjyOnFs+72V63poq+9QsvfGUbPSsGkatx1cDuWxznN/+2Qm5kWfCKcH/FIGyq5m0oSSIr7qNtIhe3aFTc8hdZs="

language: python
matrix:
  include:
  - python: "3.6"
    env: ENVLIST="py36"
  - python: "3.7"
    env: ENVLIST="py37"
  - python: "3.8"
    env: ENVLIST="py38"
  - python: "3.7"
    env: MAKE="make"

addons:
  apt:
    packages:
    - libssl-dev

install: "pip install tox"
script: "./test.sh $ENVLIST"

addons:
  coverity_scan:
    project:
      name: hashbrowncipher/keypipe
      description: "A pipe oriented authenticated encryptor"
    notification_email: "hashbrowncipher@gmail.com"
    build_command: "make c"
    branch_pattern: coverity_scan
